name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMIT_TOKEN }}


      - name: Read file content
        run: |
          file_content=$(cat project1/package.json) # Replace with your file path
          echo "Content of the file:"
          echo "$file_content"
          echo "PROJECT_1=$file_content" >> $GITHUB_ENV


      - name: Set variable
        run: echo "MY_VARIABLE=Hello World" >> $GITHUB_ENV
        
      - name: Use variable
        run: |
          echo $MY_VARIABLE

      - name: Display environment variable value
        run: |
          echo "PROJECT_1 value is ${{ env.PROJECT_1 }}"

    #   - name: Make changes
    #     run: |
    #       echo "Updated content" > file.txt # Replace with your file path
    #       git config --global user.email "vishal.kumar@cloudactivelabs.com"
    #       git config --global user.name "vishalkumar-activelabs"
    #       # git pull origin main
    #       git add .
    #       git commit -m "Update app.js"
    #       git status
    #       git push